### ISSUE TITLE
Kickstarter -> kongadapter throws error

### ISSUE THREAD

**Issue by saromba** [Haufe-Lexware/wicked.haufe.io#103]
Start the kickstarter...
docker run -it --rm -v /path/to/repo:/var/portal-api -e LOCAL_UID=$(id -u) -e LOCAL_GID=$(id -g) -p 3333:3333 haufelexware/wicked.portal-kickstarter --new 

Calling http://localhost:3333/kongadapter throws the following error:

Error: Failed to lookup view "kongAdapter" in views directory "/usr/src/app/views"
    at EventEmitter.render (/usr/src/app/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:971:7)
    at /usr/src/app/routes/kongadapter.js:12:9
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)

**Comment by DonMartin76** [comment]
@santokhsingh or @maksimlikharev - can you have a look please?

**Comment by maksimlikharev** [comment]
@saromba - what is the host operation system?

**Comment by DonMartin76** [comment]
I happen to know it's an Ubuntu Linux.
