### ISSUE TITLE
Kong-adapter write issues.

### ISSUE THREAD

**Issue by Krieke** [Haufe-Lexware/wicked.haufe.io#41]
It seems that when the kong-adapter service is restarted, that it tries to set in Kong via REST POST call again previously configured API's.  This will result in an error. Maybe it would be better this the service first check if there is already an API configured, if not create it... if so check if certain config settings require and update.

npm info using npm@3.10.8
npm info using node@v6.9.1
npm info lifecycle portal-kong-adapter@0.10.1~prestart: portal-kong-adapter@0.10.1
npm info lifecycle portal-kong-adapter@0.10.1~start: portal-kong-adapter@0.10.1
{ 'config.path': 'Cannot create file. Make sure the path is valid, and has the right permissions' }
/usr/src/app/bin/kong-adapter:62
            throw err;
            ^

Error: kongAction POST on apis/22bd42d4-f14b-49ec-90f1-d144c74110c4/plugins did not return the expected status code (got: 400, expected: 201).
    at Request._callback (/usr/src/app/kong/utils.js:124:25)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by DonMartin76** [comment]
This is this: #32 

Remove the `file-log` plugin and you will be fine.

**Comment by Krieke** [comment]
clear... issue can be closed
