### ISSUE TITLE
Failing kong adapter due to "config.origin" error 400

### ISSUE THREAD

**Issue by DonMartin76** [Haufe-Lexware/wicked.haufe.io#90]
In case the `cors` plugin is used in an API configuration, the Kong Adapter will fail with the following log error when starting a configuration which was created with the Kickstarter version<=0.12.1:

```
{ 'config.origin': 'origin is an unknown field' }
/usr/src/app/bin/kong-adapter:69
            throw err;
            ^

Error: kongAction POST on apis/79b5d620-b3eb-400f-9c0a-d303f8303cbf/plugins did not return the expected status code (got: 400, expected: 201).
    at Request._callback (/usr/src/app/kong/utils.js:212:25)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

**Workaround**: In the `config.json` of all APIs using the `cors` plugin, change the `origin` field to read `origins` instead (add an `s`).

**Comment by DonMartin76** [comment]
Fixed in 0.12.2
